import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/ldmYpFQZYObWEBvdAmK31K/RP-Design-System-3.0--MUI-6.1.0-?node-id=6543-36744&m=dev",
  {
    props: {
      startIcon: figma.boolean("Start Icon"),
      endIcon: figma.boolean("End Icon"),
      startIcon: figma.instance("↳ Start Icon"),
      endIcon: figma.instance("↳ End Icon"),
      label: figma.string("Label"),
    },
    example: (props) => <Button />,
  },
)
