name: Pull Request
on:
  pull_request:
jobs:
  jira-ticket-check:
    uses: encodium/.github/.github/workflows/jira-ticket-check.yaml@main
    secrets:
      JIRA_GITHUB_USER_EMAIL: ${{ secrets.JIRA_GITHUB_USER_EMAIL }}
      JIRA_GITHUB_USER_API_TOKEN: ${{ secrets.JIRA_GITHUB_USER_API_TOKEN }}

  dothething:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      GH_NPM_PAT: ${{ secrets.GH_PACKAGE_READ_PAT }}
    if: ${{ github.repository_owner == 'encodium' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: ''
          registry-url: "https://registry.npmjs.org"
      - name: Overwrite .npmrc
        run: |
          cp .npmrc.template .npmrc
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      - name: Lint
        run: npm run lint:ci
      - name: Test
        run: npm run test:ci
